---
- name: Perform optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Where to look
  ansible.builtin.debug:
    msg: "Have a look at https://galaxy.ansible.com/l3d/ntp"

- name: Notify about Move
  ansible.builtin.fail:
    msg: "This Project moved to l3d.ntp"
